//
//  SGFP4DequantTest.cpp
//  MNNTests
//
//  Created by MNN on 2026/08/24.
//  Copyright © 2018, Alibaba Group Holding Limited
//
#ifdef MNN_SUPPORT_TRANSFORMER_FUSE
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <sstream>
#include <vector>

#include "half.hpp"
#include "MNN_generated.h"
#include "MNN/SGFP4DequantUtils.hpp"
#include "MNN/expr/Expr.hpp"
#include "MNN/expr/ExprCreator.hpp"
#include "MNN/expr/Executor.hpp"
#include "MNN/expr/Module.hpp"
#include "MNNTestSuite.h"
#include "TestUtils.h"
#include "SGFP4DequantFixtures.h"

using namespace MNN::Express;

namespace {

// Cross-language fixture round-trip tolerance: both the encoder (Python) and
// the decoder (dequant_sgfp4_container_cpu) compute w = S*c + bias from the
// SAME FP16-truncated (S, bias) header bits, so decode should reproduce the
// fixture's `expected` values to within ordinary float32 rounding.
constexpr float kFixtureRelativeTolerance = 1e-4f;

} // namespace

class SGFP4DequantTest : public MNNTestCase {
public:
    SGFP4DequantTest()  = default;
    virtual ~SGFP4DequantTest() = default;

    virtual bool run(int precision) {
        if (!testFixtureRoundTrip()) {
            return false;
        }
        if (!testMixedDegenerateSmoke()) {
            return false;
        }
        if (!testMixedTraversalGolden()) {
            return false;
        }
        if (!testTernaryReservedSymbol()) {
            return false;
        }
        if (!testFp16LeafHeaderPrecision()) {
            return false;
        }
        if (!testMalformedContainers()) {
            return false;
        }
        if (!testOpLevelExternalSidecar()) {
            return false;
        }
        MNN_PRINT("SGFP4DequantTest: all layers PASSED\n");
        return true;
    }

private:
    // ====================================================================
    // Layer 1: cross-language fixture round-trip (SGV2-01, 02, 04, 07).
    // Fixtures are generated by tools/fp4/encode_sgfp4.py (the independent
    // Python oracle), covering both modes x all 5 uniform layouts plus a
    // B != 0 (mod 4) alignment case.
    // ====================================================================
    bool testFixtureRoundTrip() {
        for (size_t i = 0; i < sgfp4_fixtures::kFixtureCount; ++i) {
            const auto& fixture = sgfp4_fixtures::kFixtures[i];
            std::vector<float> out(fixture.expectedCount, 0.0f);
            bool ok = MNN::dequant_sgfp4_container_cpu(fixture.container, fixture.containerSize, out.data(),
                                                        fixture.expectedCount);
            if (!ok) {
                MNN_ERROR("SGFP4DequantTest: fixture '%s' decode returned false\n", fixture.name);
                return false;
            }
            if (!checkVectorByRelativeError<float>(out.data(), fixture.expected,
                                                    static_cast<int>(fixture.expectedCount),
                                                    kFixtureRelativeTolerance)) {
                MNN_ERROR("SGFP4DequantTest: fixture '%s' round-trip mismatch\n", fixture.name);
                return false;
            }
        }
        MNN_PRINT("SGFP4DequantTest: fixture round-trip (%zu cases) PASSED\n", sgfp4_fixtures::kFixtureCount);
        return true;
    }

    // ====================================================================
    // Layer 1b: degenerate LAYOUT_MIXED smoke (SGV2-08). All-zero split map
    // -> one 64x64 leaf -> must decode identically to the uniform degenerate
    // case (every element = S*code + bias with all-zero codes = bias).
    // Proves the MIXED branch runs end-to-end: walk yields one leaf, area
    // sums to 4096, block headers live at recStart + 4 + 12.
    // ====================================================================
    bool testMixedDegenerateSmoke() {
        const int leafEdge = 64;
        const int elementCount = leafEdge * leafEdge;
        const float S = 2.0f;
        const float bias = 0.5f;

        std::vector<uint8_t> container = buildSingleLeafContainer(
            MNN::kSGFP4LayoutMixed, /*mode=*/0, S, bias,
            [elementCount](std::vector<uint8_t>& payload) {
                // Every 4-bit code 0 -> w = S*0 + bias == bias.
                const int wordsPerLeaf = elementCount / MNN::kSGFP4NibblesPerWord;
                payload.assign(static_cast<size_t>(wordsPerLeaf) * 4, 0x00);
            });

        std::vector<float> out(elementCount, 0.0f);
        bool ok = MNN::dequant_sgfp4_container_cpu(container.data(), container.size(), out.data(), elementCount);
        if (!ok) {
            MNN_ERROR("SGFP4DequantTest: degenerate MIXED decode returned false\n");
            return false;
        }
        std::vector<float> expected(elementCount, bias);
        if (!checkVectorByRelativeError<float>(out.data(), expected.data(), elementCount, kFixtureRelativeTolerance)) {
            MNN_ERROR("SGFP4DequantTest: degenerate MIXED did not decode to bias\n");
            return false;
        }
        MNN_PRINT("SGFP4DequantTest: degenerate MIXED (all-zero split map) smoke PASSED\n");
        return true;
    }

    // ====================================================================
    // Layer 1c: hand-built split-map traversal golden (SGV2-08/09). Split
    // map {0x00000001, 0, 0} (bit 0 = 1 splits the 64x64 root; bits 1-4 = 0
    // leave the four 32x32 children as leaves) must decode leaves in
    // pre-order DFS order TL, TR, BL, BR -- proven without the encoder via
    // a distinct per-leaf bias marker.
    // ====================================================================
    bool testMixedTraversalGolden() {
        const int n = 32;
        const int leafElements = n * n;
        const float S = 2.0f;
        const float bias[4] = {100.0f, 101.0f, 102.0f, 103.0f}; // TL, TR, BL, BR markers

        std::vector<uint8_t> container = buildSplitFourLeafContainer(n, S, bias);
        const int elementCount = 4 * leafElements;

        std::vector<float> out(elementCount, 0.0f);
        bool ok = MNN::dequant_sgfp4_container_cpu(container.data(), container.size(), out.data(), elementCount);
        if (!ok) {
            MNN_ERROR("SGFP4DequantTest: hand-built traversal golden decode returned false\n");
            return false;
        }
        for (int k = 0; k < 4; ++k) {
            std::vector<float> expected(leafElements, bias[k]);
            if (!checkVectorByRelativeError<float>(out.data() + k * leafElements, expected.data(), leafElements,
                                                    kFixtureRelativeTolerance)) {
                MNN_ERROR("SGFP4DequantTest: leaf %d did not decode to its bias marker %f (TL/TR/BL/BR order "
                          "violation)\n", k, bias[k]);
                return false;
            }
        }
        MNN_PRINT("SGFP4DequantTest: hand-built traversal golden (TL/TR/BL/BR) PASSED\n");
        return true;
    }

    // ====================================================================
    // Layer 2a: ternary reserved symbol 11 -> 0 (SGV2-01, Pitfall 5).
    // Hand-built single-macroblock, single-leaf (LAYOUT_UNIFORM_64) mode-1
    // container whose entire payload is the reserved symbol 0b11.
    // ====================================================================
    bool testTernaryReservedSymbol() {
        const int leafEdge = 64;
        const int elementCount = leafEdge * leafEdge;
        const float S = 2.0f;
        const float bias = 0.5f;

        std::vector<uint8_t> container = buildSingleLeafContainer(
            MNN::kSGFP4LayoutUniform64, /*mode=*/1, S, bias,
            [elementCount](std::vector<uint8_t>& payload) {
                const int wordsPerLeaf = elementCount / MNN::kSGFP4SymbolsPerWord;
                payload.assign(static_cast<size_t>(wordsPerLeaf) * 4, 0x00);
                // Every 2-bit symbol = 0b11 (reserved) -> every position packs
                // to 0xFF per byte (four reserved symbols per byte).
                for (auto& b : payload) {
                    b = 0xFF;
                }
            });

        std::vector<float> out(elementCount, 0.0f);
        bool ok = MNN::dequant_sgfp4_container_cpu(container.data(), container.size(), out.data(), elementCount);
        if (!ok) {
            MNN_ERROR("SGFP4DequantTest: ternary-reserved decode returned false\n");
            return false;
        }
        // Reserved symbol decodes as code 0 -> w = S*0 + bias == bias for every element.
        std::vector<float> expected(elementCount, bias);
        if (!checkVectorByRelativeError<float>(out.data(), expected.data(), elementCount, kFixtureRelativeTolerance)) {
            MNN_ERROR("SGFP4DequantTest: ternary-reserved symbol did not decode to bias\n");
            return false;
        }
        MNN_PRINT("SGFP4DequantTest: ternary reserved symbol (11->0) PASSED\n");
        return true;
    }

    // ====================================================================
    // Layer 2b: FP16 leaf-header precision (SGV2-02), incl. the 0xFFF0
    // 12-bit truncated bias. Tests MNN::unpack_leaf_header directly against
    // an independently-computed half->float reference (FP32Converter for S,
    // manual 0xFFF0 masking for bias).
    // ====================================================================
    bool testFp16LeafHeaderPrecision() {
        const float sValue = 2.5f;
        const float biasValue = -1.75f;

        half_float::half hS(sValue);
        half_float::half hBias(biasValue);
        uint16_t sBits = 0, biasBits = 0;
        std::memcpy(&sBits, &hS, sizeof(sBits));
        std::memcpy(&biasBits, &hBias, sizeof(biasBits));
        uint16_t biasBitsMasked = biasBits & static_cast<uint16_t>(MNN::kSGFP4LeafHeaderBiasMask);

        half_float::half hBiasMasked;
        std::memcpy(&hBiasMasked, &biasBitsMasked, sizeof(hBiasMasked));
        float expectedBias = static_cast<float>(hBiasMasked);
        // FP32Converter[3] is the existing test-utility half round-trip
        // reference for S (no masking applies to S).
        float expectedS = FP32Converter[3](sValue);

        uint32_t header = (static_cast<uint32_t>(sBits) << MNN::kSGFP4LeafHeaderScaleShift) |
                           static_cast<uint32_t>(biasBitsMasked) | MNN::kSGFP4LeafHeaderModeBit; // mode = 1

        float decodedS = 0.0f, decodedBias = 0.0f;
        int decodedMode = -1;
        MNN::unpack_leaf_header(header, decodedS, decodedBias, decodedMode);

        if (decodedMode != 1) {
            MNN_ERROR("SGFP4DequantTest: leaf-header mode expected 1, got %d\n", decodedMode);
            return false;
        }
        if (std::fabs(decodedS - expectedS) > 1e-3f) {
            MNN_ERROR("SGFP4DequantTest: leaf-header S mismatch: got %f, expected %f\n", decodedS, expectedS);
            return false;
        }
        if (std::fabs(decodedBias - expectedBias) > 1e-3f) {
            MNN_ERROR("SGFP4DequantTest: leaf-header bias (0xFFF0-masked) mismatch: got %f, expected %f\n",
                       decodedBias, expectedBias);
            return false;
        }
        MNN_PRINT("SGFP4DequantTest: FP16 leaf-header precision (incl. 0xFFF0 bias mask) PASSED\n");
        return true;
    }

    // ====================================================================
    // Layer 2c: malformed containers rejected without OOB (ASVS V5).
    // Starts from a known-good fixture and mutates specific bytes located
    // via the public SGFP4DequantUtils.hpp helpers/constants (no magic
    // numbers re-derived by hand).
    // ====================================================================
    bool testMalformedContainers() {
        // mode0_uniform64 is a single-record (B=1), single-leaf (N=1)
        // fixture -- the simplest well-formed container to mutate.
        const sgfp4_fixtures::Fixture* base = nullptr;
        for (size_t i = 0; i < sgfp4_fixtures::kFixtureCount; ++i) {
            if (std::strcmp(sgfp4_fixtures::kFixtures[i].name, "mode0_uniform64") == 0) {
                base = &sgfp4_fixtures::kFixtures[i];
                break;
            }
        }
        if (nullptr == base) {
            MNN_ERROR("SGFP4DequantTest: could not locate 'mode0_uniform64' fixture for malformed-input tests\n");
            return false;
        }
        std::vector<uint8_t> good(base->container, base->container + base->containerSize);
        std::vector<float> scratch(base->expectedCount, 0.0f);

        // Sanity: the unmutated copy must still decode successfully.
        if (!MNN::dequant_sgfp4_container_cpu(good.data(), good.size(), scratch.data(), scratch.size())) {
            MNN_ERROR("SGFP4DequantTest: baseline fixture copy unexpectedly failed to decode\n");
            return false;
        }

        // (a) Bad magic.
        {
            std::vector<uint8_t> bad = good;
            bad[0] ^= 0xFF;
            if (MNN::dequant_sgfp4_container_cpu(bad.data(), bad.size(), scratch.data(), scratch.size())) {
                MNN_ERROR("SGFP4DequantTest: bad-magic container was accepted\n");
                return false;
            }
        }

        // (b) Bad version.
        {
            std::vector<uint8_t> bad = good;
            bad[MNN::kSGFP4VersionByteOffset] = 0xFF;
            if (MNN::dequant_sgfp4_container_cpu(bad.data(), bad.size(), scratch.data(), scratch.size())) {
                MNN_ERROR("SGFP4DequantTest: bad-version container was accepted\n");
                return false;
            }
        }

        // (c) Out-of-bounds record offset.
        {
            std::vector<uint8_t> bad = good;
            size_t offEntry = MNN::kSGFP4RecordOffsetTableStart; // B=1 -> single entry, at the table start
            uint32_t oobOffset = 0xFFFFFFFFu;
            std::memcpy(bad.data() + offEntry, &oobOffset, sizeof(oobOffset));
            if (MNN::dequant_sgfp4_container_cpu(bad.data(), bad.size(), scratch.data(), scratch.size())) {
                MNN_ERROR("SGFP4DequantTest: out-of-bounds record offset was accepted\n");
                return false;
            }
        }

        // (d) LAYOUT_MIXED (enum 4) -- degenerate adaption of a uniform
        // record: enum nibble mutated to MIXED and the container truncated
        // right after the 12-byte split-map region, so the (all-zero, i.e.
        // single 64x64 leaf) map parses but zero block headers / payload
        // follow. Deterministic rejection: blockHeadersStart == containerSize
        // guarantees blockHeadersBytes > containerSize - blockHeadersStart
        // for any leaf count >= 1 (T-02-02/T-02-03 posture).
        {
            std::vector<uint8_t> bad = good;
            uint32_t B = 0;
            std::memcpy(&B, bad.data() + MNN::kSGFP4RecordCountOffset, sizeof(B));
            size_t regionStart = MNN::sgfp4_align16(MNN::kSGFP4RecordOffsetTableStart +
                                                     MNN::kSGFP4RecordOffsetEntrySize * static_cast<size_t>(B));
            uint32_t recOffRel = 0;
            std::memcpy(&recOffRel, bad.data() + MNN::kSGFP4RecordOffsetTableStart, sizeof(recOffRel));
            size_t recStart = regionStart + recOffRel;
            bad[recStart] = static_cast<uint8_t>((bad[recStart] & ~MNN::kSGFP4LayoutEnumMask) |
                                                  MNN::kSGFP4LayoutMixed);
            bad.resize(recStart + 4 + MNN::kSGFP4SplitMapBytes);
            if (MNN::dequant_sgfp4_container_cpu(bad.data(), bad.size(), scratch.data(), scratch.size())) {
                MNN_ERROR("SGFP4DequantTest: malformed MIXED record (truncated after split map) was accepted\n");
                return false;
            }
        }

        MNN_PRINT("SGFP4DequantTest: malformed-container negative cases PASSED\n");
        return true;
    }

    // ====================================================================
    // Layer 3: op-level end-to-end decode via the CPU backend, using
    // rtmgr->setExternalFile + a directly-set Op.externalPath (see
    // buildAndRunSgfp4Module for the plumbing rationale).
    // ====================================================================
    bool testOpLevelExternalSidecar() {
        const sgfp4_fixtures::Fixture* fixture = nullptr;
        for (size_t i = 0; i < sgfp4_fixtures::kFixtureCount; ++i) {
            if (std::strcmp(sgfp4_fixtures::kFixtures[i].name, "mode0_uniform64") == 0) {
                fixture = &sgfp4_fixtures::kFixtures[i];
                break;
            }
        }
        if (nullptr == fixture) {
            MNN_ERROR("SGFP4DequantTest: could not locate 'mode0_uniform64' fixture for op-level test\n");
            return false;
        }

        std::ostringstream oss;
        oss << "sgfp4_test_sidecar_" << static_cast<unsigned long>(std::time(nullptr)) << "_"
            << static_cast<unsigned long>(rand()) << ".mnn.weight";
        std::string sidecarPath = oss.str();

        {
            std::ofstream ofs(sidecarPath, std::ios::binary | std::ios::trunc);
            if (!ofs) {
                MNN_ERROR("SGFP4DequantTest: failed to open sidecar '%s' for write\n", sidecarPath.c_str());
                return false;
            }
            ofs.write(reinterpret_cast<const char*>(fixture->container),
                      static_cast<std::streamsize>(fixture->containerSize));
        }

        bool pass = runSgfp4Module(sidecarPath, *fixture);
        std::remove(sidecarPath.c_str());
        return pass;
    }

    bool runSgfp4Module(const std::string& sidecarPath, const sgfp4_fixtures::Fixture& fixture) {
        std::shared_ptr<MNN::OpT> op(new MNN::OpT);
        op->type = MNN::OpType_SGFP4Dequant;
        op->main.type = MNN::OpParameter_SGFP4DequantParam;
        auto* param = new MNN::SGFP4DequantParamT;
        param->magic = MNN::kSGFP4Magic;
        param->external = {0, static_cast<int64_t>(fixture.containerSize)};
        param->dims = {fixture.dimO, fixture.dimI};
        op->main.value = param;
        // Op.externalPath (a literal per-Op string field, distinct from the
        // Pipeline/RuntimeManager-level external file) is what
        // CPUSGFP4Dequant::onResize actually reads (mirrors
        // ConvolutionCommon's op->externalPath() usage). Unlike
        // Convolution2D/Scale/LayerNorm, OpType_SGFP4Dequant is not one of
        // the types OpCommonUtils::createExecutionWithExternal rewrites to
        // inject a session-derived externalPath, so it must be set directly
        // on the Op here for the sidecar to resolve.
        op->externalPath = sidecarPath;

        // SGFP4Dequant is a 0-input, Const-like source op: output geometry
        // comes entirely from SGFP4DequantParam::dims (ShapeSGFP4Dequant),
        // not from any input tensor.
        auto output = Variable::create(Expr::create(op.get(), {}));
        auto buffer = Variable::save({output});

        MNN::ScheduleConfig config;
        config.type = MNN_FORWARD_CPU;
        std::shared_ptr<Executor::RuntimeManager> rtmgr(Executor::RuntimeManager::createRuntimeManager(config));
        // Belt-and-suspenders with the session-level external file setter
        // (Pitfall 2, resolved in 01-01-SUMMARY.md): harmless for this op
        // even though CPUSGFP4Dequant does not consume it directly.
        rtmgr->setExternalFile(sidecarPath);

        std::shared_ptr<Module> m(Module::load({}, {}, reinterpret_cast<const uint8_t*>(buffer.data()),
                                                buffer.size(), rtmgr));
        if (nullptr == m) {
            MNN_ERROR("SGFP4DequantTest: Module::load returned null\n");
            return false;
        }

        auto outputs = m->onForward({});
        if (outputs.empty()) {
            MNN_ERROR("SGFP4DequantTest: op-level module produced no outputs\n");
            return false;
        }
        auto outVar = outputs[0];
        auto* outPtr = outVar->readMap<float>();
        auto outInfo = outVar->getInfo();
        if (nullptr == outPtr || nullptr == outInfo) {
            MNN_ERROR("SGFP4DequantTest: op-level output has no data/info\n");
            return false;
        }
        size_t outCount = static_cast<size_t>(outInfo->size);
        if (outCount != fixture.expectedCount) {
            MNN_ERROR("SGFP4DequantTest: op-level output element count %zu != expected %zu\n", outCount,
                       fixture.expectedCount);
            return false;
        }
        if (!checkVectorByRelativeError<float>(outPtr, fixture.expected, static_cast<int>(outCount),
                                                kFixtureRelativeTolerance)) {
            MNN_ERROR("SGFP4DequantTest: op-level decode mismatch\n");
            return false;
        }
        MNN_PRINT("SGFP4DequantTest: op-level end-to-end decode via setExternalFile PASSED\n");
        return true;
    }

    // ====================================================================
    // Helper: pack a leaf header word (S in the high 16 bits, 0xFFF0-masked
    // bias, mode in bit 0) exactly as the spec's Eq. 6 inverse.
    // ====================================================================
    static uint32_t packLeafHeaderWord(float S, float bias, int mode) {
        half_float::half hS(S);
        half_float::half hBias(bias);
        uint16_t sBits = 0, biasBits = 0;
        std::memcpy(&sBits, &hS, sizeof(sBits));
        std::memcpy(&biasBits, &hBias, sizeof(biasBits));
        biasBits &= static_cast<uint16_t>(MNN::kSGFP4LeafHeaderBiasMask);
        return (static_cast<uint32_t>(sBits) << MNN::kSGFP4LeafHeaderScaleShift) |
               static_cast<uint32_t>(biasBits) | (static_cast<uint32_t>(mode) & 0x1u);
    }

    // ====================================================================
    // Helper: hand-build a single-macroblock LAYOUT_MIXED container whose
    // split map is {0x00000001, 0, 0} (root split, four square leaves of
    // edge n in TL/TR/BL/BR), with per-leaf S/bias and all-zero-coded mode-0
    // payloads. Independent of buildSingleLeafContainer and of the encoder.
    // ====================================================================
    std::vector<uint8_t> buildSplitFourLeafContainer(int n, float S, const float bias[4]) {
        const uint32_t B = 1;
        std::vector<uint8_t> container;
        auto appendU32 = [&container](uint32_t v) {
            container.push_back(static_cast<uint8_t>(v & 0xFF));
            container.push_back(static_cast<uint8_t>((v >> 8) & 0xFF));
            container.push_back(static_cast<uint8_t>((v >> 16) & 0xFF));
            container.push_back(static_cast<uint8_t>((v >> 24) & 0xFF));
        };

        // Fixed header: magic(4) + version(1) + B(4) + pad0(7) = 16 bytes.
        container.push_back('S');
        container.push_back('G');
        container.push_back('F');
        container.push_back('4');
        container.push_back(MNN::kSGFP4Version);
        appendU32(B);
        container.resize(MNN::kSGFP4FixedHeaderSize, 0x00);

        appendU32(0); // record_offsets[0] = 0
        container.resize(MNN::sgfp4_align16(container.size()), 0x00);

        // Record: sb_header(MIXED) + split map (bit 0 = 1) + 4 block headers.
        appendU32(MNN::kSGFP4LayoutMixed & MNN::kSGFP4LayoutEnumMask);
        appendU32(0x00000001u); // split map word 0: bit 0 splits the root
        appendU32(0x00000000u); // word 1: bits 1-4 = 0 -> 32x32 children stay leaves
        appendU32(0x00000000u); // word 2: unused, zero
        for (int k = 0; k < 4; ++k) {
            appendU32(packLeafHeaderWord(S, bias[k], /*mode=*/0));
        }
        container.resize(MNN::sgfp4_align16(container.size()), 0x00);

        // Payloads: all-zero codes (mode 0), n*n/8 words each, padded to 16B.
        const size_t payloadBytes = static_cast<size_t>(n * n / MNN::kSGFP4NibblesPerWord) * 4;
        for (int k = 0; k < 4; ++k) {
            size_t start = container.size();
            container.resize(start + MNN::sgfp4_align16(payloadBytes), 0x00);
        }
        return container;
    }

    // ====================================================================
    // Helper: build a minimal single-macroblock, single-leaf v2 container
    // (LAYOUT_UNIFORM_64 unless overridden) for hand-built edge cases.
    // `fillPayload` receives a zero-initialized payload buffer of the
    // correct size (in bytes) for the caller to populate.
    // ====================================================================
    template <typename FillPayloadFn>
    std::vector<uint8_t> buildSingleLeafContainer(uint32_t layoutEnum, int mode, float S, float bias,
                                                   FillPayloadFn fillPayload) {
        uint32_t headerWord = packLeafHeaderWord(S, bias, mode);

        std::vector<uint8_t> payload;
        fillPayload(payload);

        const uint32_t B = 1;
        std::vector<uint8_t> container;
        auto appendU32 = [&container](uint32_t v) {
            container.push_back(static_cast<uint8_t>(v & 0xFF));
            container.push_back(static_cast<uint8_t>((v >> 8) & 0xFF));
            container.push_back(static_cast<uint8_t>((v >> 16) & 0xFF));
            container.push_back(static_cast<uint8_t>((v >> 24) & 0xFF));
        };

        // Fixed header: magic(4) + version(1) + B(4) + pad0(7) = 16 bytes.
        container.push_back('S');
        container.push_back('G');
        container.push_back('F');
        container.push_back('4');
        container.push_back(MNN::kSGFP4Version);
        appendU32(B);
        container.resize(MNN::kSGFP4FixedHeaderSize, 0x00);

        // record_offsets[1] = {0}, then pad1 to align16(16 + 4*B).
        appendU32(0);
        container.resize(MNN::sgfp4_align16(container.size()), 0x00);

        // Record: sb_header(4) [+ split map (12B) if LAYOUT_MIXED] +
        // block_headers[1](4) + pad to 16B + payload.
        appendU32(layoutEnum & MNN::kSGFP4LayoutEnumMask);
        if (layoutEnum == MNN::kSGFP4LayoutMixed) {
            // All-zero split map: the 64x64 root is a single leaf.
            container.insert(container.end(), MNN::kSGFP4SplitMapBytes, 0x00);
        }
        appendU32(headerWord);
        container.resize(MNN::sgfp4_align16(container.size()), 0x00);
        container.insert(container.end(), payload.begin(), payload.end());
        container.resize(container.size() + (MNN::sgfp4_align16(payload.size()) - payload.size()), 0x00);

        return container;
    }
};

MNNTestSuiteRegister(SGFP4DequantTest, "op/sgfp4/uniform_decode");

#endif // MNN_SUPPORT_TRANSFORMER_FUSE
