#!/usr/bin/env python3
"""Author the structured (LAYOUT_MIXED) SGFP4 v2 test fixture header.

One-time authoring tool (Plan 07-02, D-01/D-02/D-03): calls the REAL gnus-poc
encoder (``quantize.fp4_exporter.FP4Exporter.export_weights(..., adaptive=True)``)
on a deterministic structured weight matrix and bakes the container bytes into
``test/op/SGFP4StructuredFixtures.h`` as a C-array fixture. The cross-repo
dependency exists at AUTHORING TIME ONLY -- no test or CI run ever executes
Python (D-03).

Determinism contract (regeneration must be byte-identical):
- No date/timestamp in the emitted provenance block.
- No unseeded RNG anywhere in the weight recipe.

Usage (from the MNN repo root):
    python tools/fp4/author_structured_fixture.py [output_header_path]
Default output_header_path: test/op/SGFP4StructuredFixtures.h
"""

import hashlib
import sys
from pathlib import Path

# Locate the gnus-poc repo (override only if your checkout lives elsewhere).
GNUST_POC_ROOT = Path("W:/gnus/GeniusCognitiveSystem/GNUS-NEO-SWARM/gnus-poc")
sys.path.insert(0, str(GNUST_POC_ROOT))

import numpy as np  # noqa: E402

from quantize.fp4_exporter import FP4Exporter  # noqa: E402

# Fixture geometry: mirrors the Phase 6 classic-API dims (D-05).
DIM_O = 512
DIM_I = 512

# Layout enum value for LAYOUT_MIXED in the quadtree classifier.
LAYOUT_MIXED = 4


def build_structured_weights() -> np.ndarray:
    """Deterministic structured 512x512 float32 weight matrix.

    Recipe (guards the all-uniform trap -- the exporter's __main__ dummy-noise
    lineage collapses to uniform superblocks):
    - Most 64x64 superblocks are near-constant (amplitude far below the
      64-size split gate), so their quadtree stays uniform.
    - A deterministic subset of superblocks carries an asymmetric structure: a
      diagonal ramp confined to the top-left 32x32 quadrant of the superblock
      (other quadrants near-constant), forcing the quadtree to split to
      different leaf depths within one superblock (only TL splits further --
      asymmetric, NOT symmetric quadrant constants which FP4 affine represents
      exactly and the tree may stay uniform).
    """
    weights = np.full((DIM_O, DIM_I), 0.002, dtype=np.float32)
    rng = np.random.default_rng(20260828)
    # Deterministic low-amplitude background texture (seeded -> reproducible).
    weights += (rng.random((DIM_O, DIM_I)).astype(np.float32) - 0.5) * 0.0005

    # Structured superblocks: every 2nd row / 3rd column (85 total), each with
    # a diagonal ramp of amplitude ~12 confined to its top-left 32x32 quadrant
    # (other quadrants stay at the background level). Amplitude 12 puts the
    # whole-block quantization MSE (~0.05) far above the size-64 gate (0.01)
    # -> split; the flat children then accept exactly while the ramp child
    # keeps splitting to different depths -> LAYOUT_MIXED (Phase 2 encoder
    # finding: TL-quadrant ramp amp 12 = asymmetric MIXED; symmetric quadrant
    # constants are exactly representable and stay uniform).
    for sb_y in range(0, DIM_O // 64, 2):
        for sb_x in range(0, DIM_I // 64, 3):
            y0, x0 = sb_y * 64 + 32, sb_x * 64 + 32
            y1, x1 = y0 + 32, x0 + 32
            ramp = np.linspace(0.05, 12.0, 32, dtype=np.float32)
            patch = 0.002 + np.outer(ramp, ramp.copy()).astype(np.float32) / 12.0
            weights[y0:y1, x0:x1] = patch
    return weights


def main() -> int:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("test/op/SGFP4StructuredFixtures.h")

    weights = build_structured_weights()
    exporter = FP4Exporter()
    binary, stats = exporter.export_weights(weights, "phase7_structured", adaptive=True)

    # Mandatory MIXED self-assert (loud failure, never silent -- Pitfall 2).
    # Index 4 = Layout.MIXED in the exporter's layout_distribution dict.
    assert stats["layout_distribution"][4] > 0
    layout_distribution = stats["layout_distribution"]
    mixed_count = int(layout_distribution[LAYOUT_MIXED])

    # Framing validation before emitting.
    if len(binary) < 5 or binary[0:4] != b"SGF4" or binary[4] != 0x02:
        print(f"FATAL: bad framing (magic/version) on {len(binary)} bytes", file=sys.stderr)
        return 1

    digest = hashlib.sha256(binary).hexdigest()

    # ---- Emit the header --------------------------------------------------
    lines = []
    lines.append("// Auto-generated by tools/fp4/author_structured_fixture.py.")
    lines.append("// DO NOT EDIT BY HAND -- regenerate via:")
    lines.append("//   python tools/fp4/author_structured_fixture.py test/op/SGFP4StructuredFixtures.h")
    lines.append("//")
    lines.append("// Provenance: structured (LAYOUT_MIXED) SGFP4 v2 container exported by the REAL")
    lines.append("// gnus-poc encoder (FP4Exporter.export_weights(..., adaptive=True)) at authoring")
    lines.append("// time. Weight recipe: deterministic 512x512 float32 -- near-constant background")
    lines.append("// (amplitude 0.002 +/- 0.00025 seeded texture), every 2nd-row/3rd-column 64x64")
    lines.append("// superblock carries an asymmetric diagonal ramp (~0.05..12.0) confined to its")
    lines.append("// top-left 32x32 quadrant so the quadtree must split to different leaf depths.")
    lines.append(f"// layout_distribution: {dict(sorted(layout_distribution.items()))}")
    lines.append(f"// LAYOUT_MIXED (enum 4) superblock count: {mixed_count}")
    lines.append(f"// container sha256: {digest}")
    lines.append(f"// container bytes: {len(binary)}")
    lines.append("#ifndef SGFP4StructuredFixtures_h")
    lines.append("#define SGFP4StructuredFixtures_h")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("static const unsigned char kStructuredMixedData[] = {")
    hex_lines = []
    for i in range(0, len(binary), 16):
        chunk = binary[i:i + 16]
        hex_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    hex_lines[-1] = hex_lines[-1].rstrip(",")
    lines.extend(hex_lines)
    lines.append("};")
    lines.append("")
    lines.append(f"constexpr int kStructuredDimO = {DIM_O};")
    lines.append(f"constexpr int kStructuredDimI = {DIM_I};")
    lines.append("constexpr size_t kStructuredSize = sizeof(kStructuredMixedData);")
    lines.append(f"// Documentation-only provenance: MIXED superblock count at authoring time (the")
    lines.append(f"// C++ side cannot re-derive MIXED-ness from the bytes without a full re-classify).")
    lines.append(f"constexpr int kStructuredMixedCount = {mixed_count};")
    lines.append("")
    lines.append("#endif // SGFP4StructuredFixtures_h")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="ascii", newline="\n")

    print(f"wrote {out_path}: {len(binary)} bytes, sha256 {digest}")
    print(f"layout_distribution: {dict(sorted(layout_distribution.items()))}")
    print(f"MIXED superblocks: {mixed_count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
