#!/usr/bin/env python3
"""Author the real-shape SGFP4 v2 test fixture header (Plan 09-03, D-05).

Calls the REAL gnus-poc encoder (quantize.fp4_exporter.FP4Exporter
.export_weights(..., adaptive=True)) on seeded pseudo-random FP32 weight
matrices of non-64-aligned, tiny, one-dim-aligned, and fully-aligned shapes,
then bakes three arrays per fixture into test/op/SGFP4RealShapeFixtures.h:
inputWeights (FP32 source plane), container (Python-encoded SGFP4 v2 bytes),
expected (decoded reference via the gnus-poc decode_v2 oracle). The C++
parity suites (Plans 09-04/09-05) feed inputWeights through
sgfp4_encode::encode() and compare C++-decode vs this Python reference at
rtol 1e-4. The cross-repo dependency exists at AUTHORING TIME ONLY.

Determinism contract (regeneration must be byte-identical):
- No date/timestamp in the emitted provenance block.
- Per-shape seeded RNG (np.random.default_rng(20260828 + dimO*1000 + dimI)).

Usage (from the MNN repo root):
    python tools/fp4/author_real_shape_fixture.py [output_header_path]
Default output_header_path: test/op/SGFP4RealShapeFixtures.h
"""

import hashlib
import os
import sys
from pathlib import Path

# Locate the gnus-poc repo. W-3 (Phase 11, D-11): root overridable via the
# SGFP4_GNUS_POC_ROOT env var, falling back to the original hard-coded path
# (no gnus-poc-side convention exists -- the name is MNN-side).
GNUST_POC_ROOT = Path(os.environ.get("SGFP4_GNUS_POC_ROOT", "W:/gnus/GeniusCognitiveSystem/GNUS-NEO-SWARM/gnus-poc"))
sys.path.insert(0, str(GNUST_POC_ROOT))

import numpy as np  # noqa: E402

from quantize.fp4_exporter import FP4Exporter  # noqa: E402
from quantize.sgfp4_decoder import decode_v2  # noqa: E402

# Fixture shapes: non-64-aligned, tiny, one-dim-aligned, fully-aligned (D-05;
# 128x64 fully aligned is required by the Plan 09-05 aligned-leg test).
SHAPES = [
    (100, 36, "shape_100x36"),
    (250, 128, "shape_250x128"),
    (37, 91, "shape_37x91"),
    (64, 36, "shape_64x36"),    # dimO 64-aligned, dimI not
    (5, 5, "shape_5x5"),        # tiny: single superblock, mostly pad
    (1, 1, "shape_1x1"),        # extreme tiny
    (128, 64, "shape_128x64"),  # fully 64-aligned (Plan 09-05 aligned leg)
]


def float_c_array(values, per_line=8):
    lines = []
    flat = list(values)
    for i in range(0, len(flat), per_line):
        chunk = flat[i:i + per_line]
        lines.append("    " + ", ".join(f"{v:.6e}f" for v in chunk) + ",")
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return lines


def byte_c_array(data, per_line=16):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return lines


def main() -> int:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("test/op/SGFP4RealShapeFixtures.h")

    exporter = FP4Exporter()
    fixtures = []

    for dim_o, dim_i, name in SHAPES:
        rng = np.random.default_rng(20260828 + dim_o * 1000 + dim_i)
        weights = (rng.standard_normal((dim_o, dim_i)).astype(np.float32) * 0.5)

        # fp4_exporter.export_weights takes the 2-D array directly (ndim==2
        # branch of _export_v2_adaptive); no shape kwarg.
        binary, stats = exporter.export_weights(weights, name, adaptive=True)
        if not binary:
            print(f"FATAL: empty export for {name}", file=sys.stderr)
            return 1
        # Framing validation before emitting (determinism contract).
        if len(binary) < 16 or binary[0:4] != b"SGF4" or binary[4] != 0x02:
            print(f"FATAL: bad framing (magic/version) for {name}", file=sys.stderr)
            return 1

        expected = decode_v2(binary, dim_o, dim_i)
        if expected.shape != (dim_o, dim_i):
            print(f"FATAL: decode_v2 returned {expected.shape} for {name}", file=sys.stderr)
            return 1

        digest = hashlib.sha256(binary).hexdigest()
        fixtures.append({
            "name": name,
            "dim_o": dim_o,
            "dim_i": dim_i,
            "weights": weights.flatten().tolist(),
            "binary": binary,
            "expected": expected.flatten().tolist(),
            "sha256": digest,
            "stats": stats,
        })

    # ---- Emit the header --------------------------------------------------
    lines = []
    lines.append("// Auto-generated by tools/fp4/author_real_shape_fixture.py.")
    lines.append("// DO NOT EDIT BY HAND -- regenerate via:")
    lines.append("//   python tools/fp4/author_real_shape_fixture.py test/op/SGFP4RealShapeFixtures.h")
    lines.append("//")
    lines.append("// Provenance: seeded pseudo-random FP32 planes encoded by the REAL gnus-poc")
    lines.append("// exporter (FP4Exporter.export_weights(..., adaptive=True)) and decoded by")
    lines.append("// quantize.sgfp4_decoder.decode_v2 at authoring time. Per-fixture sha256")
    lines.append("// provenance is embedded in the fixture-array comments.")
    lines.append("#ifndef SGFP4RealShapeFixtures_h")
    lines.append("#define SGFP4RealShapeFixtures_h")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace sgfp4_real_shape_fixtures {")
    lines.append("")
    lines.append("struct RealShapeFixture {")
    lines.append("    const char* name;")
    lines.append("    const unsigned char* container;")
    lines.append("    size_t containerSize;")
    lines.append("    int dimO;")
    lines.append("    int dimI;")
    lines.append("    const float* inputWeights;")
    lines.append("    size_t inputCount;")
    lines.append("    const float* expected;")
    lines.append("    size_t expectedCount;")
    lines.append("};")
    lines.append("")

    for fx in fixtures:
        n = fx["name"]
        lines.append(f"// ---- {n}: {fx['dim_o']}x{fx['dim_i']} ----")
        lines.append(f"// container sha256: {fx['sha256']}")
        lines.append(f"// container bytes: {len(fx['binary'])}")
        lines.append(f"static const unsigned char k{n}Container[] = {{")
        lines.extend(byte_c_array(fx["binary"]))
        lines.append("};")
        lines.append("")
        lines.append(f"static const float k{n}InputWeights[] = {{")
        lines.extend(float_c_array(fx["weights"]))
        lines.append("};")
        lines.append("")
        lines.append(f"static const float k{n}Expected[] = {{")
        lines.extend(float_c_array(fx["expected"]))
        lines.append("};")
        lines.append("")

    lines.append("static const RealShapeFixture kRealShapeFixtures[] = {")
    for fx in fixtures:
        n = fx["name"]
        count = fx["dim_o"] * fx["dim_i"]
        lines.append(
            f"    {{\"{n}\", k{n}Container, sizeof(k{n}Container), {fx['dim_o']}, {fx['dim_i']}, "
            f"k{n}InputWeights, {count}, k{n}Expected, {count}}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("static const size_t kRealShapeFixtureCount =")
    lines.append("    sizeof(kRealShapeFixtures) / sizeof(kRealShapeFixtures[0]);")
    lines.append("")
    lines.append("} // namespace sgfp4_real_shape_fixtures")
    lines.append("")
    lines.append("#endif // SGFP4RealShapeFixtures_h")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="ascii", newline="\n")

    for fx in fixtures:
        print(f"{fx['name']}: {len(fx['binary'])} bytes, sha256 {fx['sha256'][:16]}...")
    return 0


if __name__ == "__main__":
    sys.exit(main())
